name: run main.py

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Daily


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - run: uv sync
      - run: |
          export PRIVATE_KEY=${PRIVATE_KEY}
          uv run main.py
        env:
          NAMESPACE: ${{ vars.NAMESPACE }}
          DOMAIN: ${{ vars.DOMAIN }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          SETTLE_UP_API_KEY: ${{ secrets.SETTLE_UP_API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
