name: Settle Up monthly expense daily sync


# Cron minimum is 5 but not guaranteed
# Reference: https://stackoverflow.com/questions/63192132/why-does-my-cron-configured-github-action-not-run-every-2-minutes
#    - cron: '*/5 * * * *' # every 5
on:
  schedule:
    - cron: "*/5 * * * *"
  #    - cron: '0 0 * * *'   # daily - 12:00 AM UTC
  #    - cron: '0 16 * * *'  # daily - 04:00 PM UTC
  workflow_dispatch:


jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
      - run: uv sync
      - run: uv run main.py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          NAMESPACE: ${{ vars.NAMESPACE }}
          DOMAIN: ${{ vars.DOMAIN }}
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}
          SETTLE_UP_API_KEY: ${{ secrets.SETTLE_UP_API_KEY }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git status
          cat status.log
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
      - uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
